### ISSUE TITLE
Remove empty instantiations

### ISSUE THREAD

**Issue by ktk** [zazuko/amos#81] opened 2022-05-17 11:44 UTC
That used to be/is fixed but for some reasons it fails on the new pipeline.

Also we still seem to have IRIs with `//` in it at some point.

**Comment by PlekszyGladz** [comment] 2022-06-01 08:23
I checked the data for the cause of this. 

- currently instantiation-IRI are as follows: https://data.ptt-archiv.ch/archive/instantiation/{AIPReferenz}
- There are no empty instantiations but rather one 'generic' one: https://data.ptt-archiv.ch/archive/instantiation/
- This is due to the fact that in scopeArchive we can link files without writing an AIP (archival information package) into the long term storage. This results in a missing identifier (`AIPReferenz` in XRM) wich is used for the instantiation IRI. 

as we are changing the way instantiations are generated (as described here #67), maybe a new unified IRI pattern is in order?
- instantiation IRI for IIIF Manifests: https://data.ptt-archiv.ch/archive/instantiation/{ID}/iiif
- instantiation IRI for linked Files: https://data.ptt-archiv.ch/archive/instantiation/{ID}/aip
--> but this would then result in a lot of empty instantiations (with no linked filenames)

@ktk maybe we should have a short call about this?

**Comment by ktk** [comment] 2022-06-24 08:54
- [x] Move all IRI templates to a separate file and give them an alias so we can use them in the mappings
- [x] Replace `AIPReferenz` with `ID` where appropriate
- [ ] Create a SPARQL query that fetches all `Instantiation`s that are "empty", in terms of they don't have predicates attached and delete them on the insert step in the pipeline

**Comment by PlekszyGladz** [comment] 2022-07-05 12:38
- Refactored IRIs and changed `AIPReferenz` to `ID` where needed
- Also removed some mappings that are better created as some static triples (I added them here: https://gitlab.zazuko.com/amos/amos/-/tree/issue-81/static)

**Comment by ktk** [comment] 2022-09-01 09:28
Double check after #90 is done

**Comment by ktk** [comment] 2022-09-01 09:34
It could also be that we now generate IRIs that do not have any tripples attached.

WIP But not yet correct SPARQL query: https://s.zazuko.com/2zakEC

**Comment by ktk** [comment] 2022-10-27 08:49
It looks like we do have triples generated in the pipeline so we need to double check if we can skip that in the pipeline already or if we have to clean up via sparql in the end:

```sparql
prefix sortBy: <https://data.ptt-archiv.ch/sort-by#>
PREFIX rdac: <http://rdaregistry.info/Elements/c/>
prefix rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT (COUNT(?empty) AS ?count)
FROM <https://mfk.zazukoians.org/amos-test-date/archive>
{

    ?empty a rico:Instantiation ;
              <https://www.ica.org/standards/RiC/ontology#hasRepresentationType> <https://data.ptt-archiv.ch/archive/instantiation/type/aip> ; # can be iiif as well for distinction

           
    MINUS {
      ?empty <http://dbpedia.org/ontology/filename> ?filename .

    }
#FILTER( DATATYPE(?obj) = <http://www.w3.org/2001/XMLSchema#date>)
}# LIMIT 10
```

**Comment by PlekszyGladz** [comment] 2023-01-27 12:33
Finnally gotten around to writing the query catching empty instantiations. **Still WIP** as the second query needs some more verification.

AIP-Instantiations (as created by @ktk):
```sparql
prefix sortBy: <https://data.ptt-archiv.ch/sort-by#>
PREFIX rdac: <http://rdaregistry.info/Elements/c/>
prefix rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT ?empty
FROM <https://mfk.zazukoians.org/amos-test-date/archive>
{

    ?empty a rico:Instantiation ;
        <https://www.ica.org/standards/RiC/ontology#hasRepresentationType> <https://data.ptt-archiv.ch/archive/instantiation/type/aip> ; # can be iiif as well for distinction

           
    MINUS {
        ?empty <http://dbpedia.org/ontology/filename> ?filename .

    }
}# LIMIT 10
```

IIIF-Instantiations: This one is a bit trickier as the filenames are nested inside an empty manifest. **Both the empty IIIF-Instantiations and the empty Manifest need to be deleted**.
```sparql
prefix sortBy: <https://data.ptt-archiv.ch/sort-by#>
PREFIX rdac: <http://rdaregistry.info/Elements/c/>
prefix rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT ?empty
FROM <https://mfk.zazukoians.org/amos-test-date/archive>
{

    ?empty a rico:Instantiation ;
        <https://www.ica.org/standards/RiC/ontology#hasRepresentationType> <https://data.ptt-archiv.ch/archive/instantiation/type/iiif> ;
            <http://www.loc.gov/premis/rdf/v3/storedAt> ?manifest .


           
    MINUS {
        ?manifest <http://example.org/fileNames> ?filename .

    }
}# LIMIT 10
```

**Comment by tpluscode** [comment] 2023-04-06 07:26
@PlekszyGladz here are the result of removing empty instantiations in a test graph. Here are the queries above adjusted for that graph:
 
- API-Instantiations: https://s.zazuko.com/2PJAbw2
- IIIF-Instantiations: https://s.zazuko.com/5Vi2iQ

Please let me know if there are additional refinements required?

**Comment by tpluscode** [comment] 2023-04-24 08:50
@PlekszyGladz I just pushed an update to the branch. When the pipeline is done, the only empty IIIF instantiations should be  removed.

Graph `https://mfk.zazukoians.org/amos-test-empty-inst/archive`

**Comment by PlekszyGladz** [comment] 2023-04-26 07:50
checked and worked perfectly. @tpluscode can be merged and closed :)

**Comment by tpluscode** [comment] 2023-04-26 08:12
Thanks. Merged

**Closed as completed by tpluscode** 2023-04-26 08:12 UTC
